modLoader="scorge"
loaderVersion="[3,)"

[[mods]]
version="1.0.0"
authors="ustc-zzzz"
modId="watersprayer"
displayName="Water Sprayer"
description="Water Sprayer Mod"
entryClass="com.github.ustc_zzzz.watersprayer.WaterSprayerMod"

[[dependencies.watersprayer]]
modId="forge"
mandatory=true
versionRange="[31,)"
ordering="NONE"
side="BOTH"

[[dependencies.watersprayer]]
modId="minecraft"
mandatory=true
versionRange="[1.15.2]"
ordering="NONE"
side="BOTH"
